<script lang="ts">
	/**
	 * The live invitation preview.
	 *
	 * It renders in the browser from the *same* layout module the PDF writer uses, so
	 * moving a control moves the preview immediately -- no server round trip, and no
	 * chance of the preview and the print disagreeing about where anything sits.
	 *
	 * The QR code is fetched once per household rather than per keystroke: it depends
	 * only on the link, so retyping the venue must not refetch it.
	 */
	import { invitationSvg } from '$shared/invitation-svg';
	import type { InvitationText } from '$shared/invitation-layout';

	let {
		text,
		widthIn,
		heightIn,
		variant,
		bleedIn = 0,
		showCropMarks = false,
		householdId
	}: {
		text: InvitationText;
		widthIn: number;
		heightIn: number;
		variant: 'full' | 'insert';
		bleedIn?: number;
		showCropMarks?: boolean;
		householdId: string | null;
	} = $props();

	let qrDataUrl = $state<string | null>(null);

	$effect(() => {
		if (!householdId || !text.showQr) {
			qrDataUrl = null;
			return;
		}

		const controller = new AbortController();

		// Keyed on the household alone. The endpoint returns a data URL rather than a
		// file so it can be inlined straight into the SVG.
		fetch(`/invitations/qr?household=${encodeURIComponent(householdId)}`, {
			signal: controller.signal
		})
			.then((response) => (response.ok ? response.json() : null))
			.then((payload: { dataUrl: string } | null) => {
				if (payload) qrDataUrl = payload.dataUrl;
			})
			.catch(() => {
				// A failed fetch just leaves the placeholder square; the layout still reads.
			});

		return () => controller.abort();
	});

	const svg = $derived(
		invitationSvg(text, { widthIn, heightIn, variant, bleedIn, showCropMarks, qrDataUrl })
	);
</script>

<div class="rounded-xl border border-line bg-sunken p-4">
	<!--
		Generated by $shared/invitation-svg from typed layout operations -- there is no
		path by which an admin's text reaches this as markup, because every string goes
		through escapeHtml on the way in.
	-->
	<div class="mx-auto max-w-[22rem] shadow-lift">{@html svg}</div>

	<p class="mt-3 text-center text-xs text-muted">
		{widthIn} &times; {heightIn} in{bleedIn > 0 ? ` + ${bleedIn}in bleed` : ''}
		&middot; exact positions, approximate letterforms
	</p>
</div>
